version: "3.9"
services:
  spring:
    image: jeet8205/restapi
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/db?autoReconnect=true&failOverReadOnly=false&maxReconnects=50
      SPRING_DATASOURCE_USERNAME: sayan
      SPRING_DATASOURCE_PASSWORD: cr78205
    depends_on:
      - mysqldb
  
  mysqldb:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=sayan
      - MYSQL_PASSWORD=cr78205
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
